//-----------------------------------------------------------------------

// <copyright file="ProcessingStage.cs" company="Breanos GmbH">
// Copyright Notice:
// DAIPAN - This file, program or part of a program is considered part of the DAIPAN framework by Breanos GmbH for Industrie 4.0
// Published in 2018 by Gerhard Eder gerhard.eder@breanos.com and Achim Bernhard achim.bernhard@breanos.com
// To the extent possible under law, the publishers have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
// You should have received a copy of the CC0 Public Domain Dedication along with this software. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
// <date>Monday, December 3, 2018 3:34:35 PM</date>
// </copyright>

//-----------------------------------------------------------------------

///////////////////////////////////////////////////////////
//  ProcessingStage.cs
//  Implementation of the Enumeration ProcessingStage
//  Generated by Enterprise Architect
//  Created on:      02-Feb-2018 10:26:56
//  Original author: bezdedeanu
///////////////////////////////////////////////////////////

namespace BlackboardClassLibrary
{
    /// <summary>
    /// This is the command processing stage
    /// </summary>
    public enum ProcessingStage : int
    {
        /// <summary>
        /// Command has been initialized
        /// </summary>
        Initialized,
        /// <summary>
        /// Command has been queued
        /// </summary>
        Queued,       
        /// <summary>
        /// Command is actioned
        /// </summary>
        Actioned
    }//end ProcessingStage
}
