// <auto-generated />
using System;
using AccessControlServiceModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AccessControlServiceModel.Migrations
{
    [DbContext(typeof(AccessControlServiceContext))]
    [Migration("20180423095305_InitialBSMigration")]
    partial class InitialBSMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccessControlServiceModel.GroupPermission", b =>
                {
                    b.Property<string>("GroupIdentification")
                        .HasMaxLength(128);

                    b.Property<long>("PermissionId");

                    b.HasKey("GroupIdentification", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("GroupPermission","ACS");
                });

            modelBuilder.Entity("AccessControlServiceModel.Permission", b =>
                {
                    b.Property<long>("PermissionId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ParentPermissionId");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("PermissionId");

                    b.HasIndex("ParentPermissionId");

                    b.ToTable("Permission","ACS");
                });

            modelBuilder.Entity("AccessControlServiceModel.GroupPermission", b =>
                {
                    b.HasOne("AccessControlServiceModel.Permission", "Permission")
                        .WithMany("Groups")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AccessControlServiceModel.Permission", b =>
                {
                    b.HasOne("AccessControlServiceModel.Permission", "ParentPermission")
                        .WithMany("ChildPermissions")
                        .HasForeignKey("ParentPermissionId");
                });
#pragma warning restore 612, 618
        }
    }
}
